"""Build the single-file RisuAI script from reviewable Lua source modules."""
from pathlib import Path
import re
from export_data import export

ROOT=Path(__file__).resolve().parent

def assemble():
    export()
    legacy=(ROOT/'src/legacy.lua').read_text(encoding='utf-8')
    core=legacy[:legacy.index('local function finishRound')]
    core=core.replace('-- Port of battle_sim_poc/battle_sim.py (1v1, no-skill POC).', '-- Generated by assemble.py; edit src/*.lua. Skill engine v2.')
    cinema=legacy[legacy.index('local function esc'):legacy.index('local function renderCharacter')]
    # Reuse asset/delta helpers, but omit the superseded portrait/stage markup.
    cinema=cinema[:cinema.index('local function mainPortraitPath')]+cinema[cinema.index('local SPECIAL_RESOLVE_SUFFIX'):]
    cinema=cinema[:cinema.index('local function cinematicImage')]+cinema[cinema.index('local function renderActionPreload'):]
    cinema=cinema.replace("if side=='player' then return 'player' end\n  return state.strategy or 'enemy'", "return (state.characterKeys or {})[side] or (side=='player' and 'player' or state.strategy or 'enemy')")
    # Lua's and/or idiom drops false/nil player values: use an explicit side lookup.
    cinema=re.sub(r"side=='player' and presentation\.(player\w+) or presentation\.(enemy\w+)",r"B.sideValue(presentation,side,'\1','\2')",cinema)
    chunks=[core, 'local B = {}\nfunction B.sideValue(t,side,p,e) if side=="player" then return t[p] end return t[e] end\n']
    for file in ['data.lua','engine.lua','ng_plus.lua']:
        chunks.append((ROOT/'src'/file).read_text(encoding='utf-8'))
    chunks.append(cinema)
    chunks.append((ROOT/'src/presentation.lua').read_text(encoding='utf-8'))
    if (ROOT/'src/ui.lua').exists(): chunks.append((ROOT/'src/ui.lua').read_text(encoding='utf-8'))
    chunks.append('if BATTLE_SIM_TEST then return B end\n')
    (ROOT/'BattleSim.lua').write_text('\n'.join(chunks),encoding='utf-8')
    css='<style>\n'+(ROOT/'src/battle.css').read_text(encoding='utf-8')+'\n'
    css+=(ROOT/'src/skills.css').read_text(encoding='utf-8')+'\n</style>\n'
    (ROOT/'BattleSim.css').write_text(css,encoding='utf-8')
    print('Assembled BattleSim.lua')

if __name__=='__main__': assemble()
