"""Export validated Python definitions; Python is required only when building/testing."""
from pathlib import Path
import dataclasses
from enum import Enum
from collections.abc import Mapping
import sys
import json

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT.parent / 'battle-sim-poc' / 'src'))
from easy_enemy_skills import load_easy_skill_registry
from muh_skills import load_muh_skill_registry
from phase_c_test_skills import PHASE_C_TEST_SKILLS
from phase_d_test_skills import PHASE_D_TEST_SKILLS
from phase_e_skill_sets import load_phase_e_skill_registry
from skill_schema import parse_skill_definition
from concept_decks import DECKS

def plain(v):
    if isinstance(v, Enum): return v.value
    if dataclasses.is_dataclass(v): return {f.name: plain(getattr(v, f.name)) for f in dataclasses.fields(v)}
    if isinstance(v, Mapping): return {k: plain(x) for k, x in v.items()}
    if isinstance(v, (tuple, list)): return [plain(x) for x in v]
    return v

def lua(v):
    if v is None: return 'nil'
    if isinstance(v, bool): return 'true' if v else 'false'
    if isinstance(v, str): return json.dumps(v, ensure_ascii=False)
    if isinstance(v, (int, float)): return repr(v)
    if isinstance(v, list): return '{' + ','.join(lua(x) for x in v) + '}'
    return '{' + ','.join('[' + lua(k) + ']=' + lua(x) for k, x in v.items() if x is not None) + '}'

def registry():
    public = {**load_easy_skill_registry(), **load_muh_skill_registry()}
    testing = {d.skill_id: d for d in map(parse_skill_definition, (*PHASE_C_TEST_SKILLS, *PHASE_D_TEST_SKILLS))}
    testing.update(load_phase_e_skill_registry())
    return public, testing

def export():
    public, testing = registry()
    data = {k: {**plain(v), 'developer': k in testing} for k, v in {**public, **testing}.items()}
    assert len(public) == 35 and len(testing) == 17
    presets = [{'id': 'empty', 'name': '빈 장착', 'skills': []},
               {'id': 'basic', 'name': '기본 3종', 'skills': ['rookie_power_strike', 'rookie_recovery_form', 'rookie_safe_footwork']}]
    presets += [{'id': k, 'name': n, 'skills': ids.split()} for k, (n, ids) in DECKS.items()]
    text = '-- Generated by export_data.py. Do not edit definitions here.\nB.skills = {\n'
    text += '\n'.join('[' + lua(k) + ']=' + lua(v) + ',' for k, v in data.items()) + '\n}\n'
    text += 'B.skillOrder = ' + lua(list(data)) + '\nB.presets = ' + lua(presets) + '\n'
    (ROOT / 'src').mkdir(exist_ok=True)
    (ROOT / 'src' / 'data.lua').write_text(text, encoding='utf-8')
    print(f'Exported {len(public)} public + {len(testing)} developer skills / {sum(len(x.levels) for x in [*public.values(), *testing.values()])} levels')

if __name__ == '__main__': export()
