-- LAST BELL 1.0.0 / generated by build.py
-- LAST BELL: a deterministic, three-beat boxing puzzle. No BattleSim engine code.
local G = {}
G.version = 1
G.key = 'last_bell_campaign_v1'
G.order = {'jab','cross','hook','body','guard','low','slip','feint','in','out','pivot','breathe','clinch'}
G.actions = {
  jab={name='잽',short='JAB',cost=4,damage=4,kind='head',range={1,2},tip='포켓·잽 거리 / 4 피해. 적중 직후 스트레이트 +4.'},
  cross={name='스트레이트',short='CROSS',cost=7,damage=8,kind='head',range={1,2},tip='포켓·잽 거리 / 8 피해. 잽 적중 또는 슬립 성공 직후 +4.'},
  hook={name='훅',short='HOOK',cost=8,damage=11,kind='head',range={1},tip='포켓 전용 / 11 피해. 슬립을 잡지만 거리가 벌어지면 빗나감.'},
  body={name='바디',short='BODY',cost=6,damage=4,kind='body',range={0,1,2},tip='밀착~잽 거리 / 4 피해·호흡 7 감소. 하이 가드 공략.'},
  guard={name='하이 가드',short='HIGH',cost=0,tip='머리 피해 70% 감소. 바디는 막지 못함.'},
  low={name='로우 가드',short='LOW',cost=0,tip='바디 피해·호흡 손실 80% 감소. 머리 피해는 20% 증가.'},
  slip={name='슬립',short='SLIP',cost=3,tip='잽·스트레이트 회피. 성공 직후 펀치 +4. 훅·바디에는 무방비.'},
  feint={name='페인트',short='FEINT',cost=2,tip='다음 박자 펀치 +2. 상대가 이 박자 가드라면 다음 펀치가 가드 관통.'},
  ['in']={name='전진',short='STEP IN',cost=2,move=-1,tip='한 칸 접근하고 상대를 로프로 압박. 이번 박자는 공격하지 않음.'},
  out={name='후퇴',short='STEP OUT',cost=2,move=1,tip='한 칸 벌리며 내 로프 압박 +1. 압박 2에서는 후퇴 불가.'},
  pivot={name='피벗',short='PIVOT',cost=3,tip='내 로프 압박을 0으로. 거리 유지·머리 피해 30% 감소.'},
  breathe={name='호흡',short='BREATHE',cost=0,tip='기본 회복에 추가 호흡 +7·충격 -3. 방어 효과는 없음.'},
  clinch={name='클린치',short='CLINCH',cost=4,tip='밀착·포켓에서 양쪽 공격을 중단. 중앙 잽 거리로 복귀·충격 -4.'}
}
G.styles = {
  {id='reader',name='아웃복서',tag='READ & RETURN',desc='슬립·피벗 비용 -1. 회피로 기회를 만드는 선수.'},
  {id='pressure',name='인파이터',tag='CLOSE THE GAP',desc='훅·바디 피해 +2. 가까이 붙어 호흡을 무너뜨리는 선수.'},
  {id='engine',name='페이스메이커',tag='STAY THE DISTANCE',desc='최대 호흡 +6. 긴 경기와 공격 연속 배치에 유리.'}
}
G.rivals = {
  {name='한도윤',alias='THE METRONOME',venue='동네 체육관',color='#78cfc3',rounds=2,hp=65,sta=26,power=0,
   quote='박자를 알면, 주먹이 보인다.',lesson='잽·스트레이트에는 슬립. 하이 가드가 보이면 바디. 먼저 기본 패턴을 익히세요.',
   patterns={{'jab','cross','breathe'},{'guard','jab','cross'},{'in','body','guard'}}},
  {name='백태오',alias='IRON TIDE',venue='항구 창고 링',color='#efa170',rounds=3,hp=82,sta=30,power=1,
   quote='물러날 곳이 언제까지 있을까?',lesson='전진 뒤 훅이 이어집니다. 후퇴로 훅을 비우되 로프 압박 2가 되기 전에 피벗하세요.',
   patterns={{'in','hook','body'},{'in','body','hook'},{'guard','breathe','cross'},{'jab','in','hook'}}},
  {name='서이서',alias='GLASS NEEDLE',venue='옥상 야간 리그',color='#b3a0f3',rounds=3,hp=78,sta=32,power=1,
   quote='네가 던지기 전에, 나는 비어 있어.',lesson='슬립을 잽으로 쫓지 마세요. 포켓에서 훅을 노리거나 바디로 호흡을 빼앗으세요.',
   patterns={{'slip','cross','out'},{'jab','slip','cross'},{'in','slip','hook'},{'low','jab','breathe'}}},
  {name='권무진',alias='THE LOCK',venue='시민 챔피언십',color='#e5c477',rounds=4,hp=104,sta=32,power=1,
   quote='문은 없다. 네가 만들어야 한다.',lesson='가드를 향한 페인트 다음 펀치는 방어를 관통합니다. 높은 가드와 낮은 가드를 구분하세요.',
   patterns={{'guard','guard','cross'},{'low','body','guard'},{'in','guard','hook'},{'guard','breathe','body'}}},
  {name='윤세라',alias='LAST LIGHT',venue='미드나이트 타이틀전',color='#f17788',rounds=4,hp=110,sta=36,power=2,
   quote='마지막 종이 울릴 때, 누가 서 있을까?',lesson='반복한 첫 행동에 다음 교환부터 대응합니다. 예고는 확정되어 있으니 변화를 읽고 계획하세요.',
   patterns={{'feint','cross','hook'},{'in','body','cross'},{'slip','cross','guard'},{'jab','out','breathe'},{'guard','body','hook'}}}
}
G.upgrades = {
  {id='lungs',name='로드워크',desc='최대 호흡 +4',max=3},
  {id='power',name='샌드백',desc='모든 펀치 피해 +1',max=3},
  {id='heart',name='기초 체력',desc='최대 체력 +8',max=3}
}

local function clamp(x,a,b) return math.max(a,math.min(b,x)) end
local function copy(t) if type(t)~='table' then return t end local n={} for k,v in pairs(t) do n[k]=copy(v) end return n end
G.copy=copy
G.clamp=clamp
function G.new(seed,serial)
  return {version=1,revision=0,serial=serial or 1,seed=seed or 1701,screen='home',style='reader',level=1,points=0,
    upgrades={lungs=0,power=0,heart=0},records={},wins=0,losses=0,help=false}
end
local function random(s,n) s.seed=(s.seed*48271)%2147483647 return s.seed%n+1 end
function G.fighter(hp,sta,power,style)
  return {hp=hp,maxhp=hp,sta=sta,maxsta=sta,power=power or 0,style=style or 'rival',shock=0,downs=0,
    ropes=0,combo='',opening=false,rdDamage=0,rdDowns=0,hits=0,damage=0}
end
function G.cost(f,id)
  local c=G.actions[id].cost
  if f.style=='reader' and (id=='slip' or id=='pivot') then c=c-1 end
  return c
end
function G.forecast(s)
  local m=s.match; local r=G.rivals[s.level]
  local i=random(s,#r.patterns)
  if m.pattern==i then i=i%#r.patterns+1 end
  m.pattern=i; m.intent=copy(r.patterns[i]); m.adapt=''
  -- Adapt only between exchanges, before the player edits their next plan.
  if s.level==5 and m.lastFirst then
    if m.lastFirst=='jab' or m.lastFirst=='cross' then m.intent[1]='slip'; m.adapt='지난 첫 펀치를 읽고 슬립 준비.'
    elseif m.lastFirst=='guard' then m.intent[1]='body'; m.adapt='지난 하이 가드를 읽고 바디 준비.'
    elseif m.lastFirst=='out' then m.intent[1]='in'; m.adapt='지난 후퇴를 읽고 전진 준비.' end
  end
  if m.e.sta<10 then m.intent[1]='guard'; m.intent[2]='breathe'; m.adapt='호흡을 회복하려고 템포를 낮춥니다.' end
end
function G.start(s)
  local r=G.rivals[s.level]; local u=s.upgrades
  s.match={p=G.fighter(100+u.heart*8,30+u.lungs*4+(s.style=='engine' and 6 or 0),u.power,s.style),
    e=G.fighter(r.hp,r.sta,r.power),round=1,exchange=1,distance=2,plan={},cards={},log={},turn=0,
    last={},rounds=r.rounds,totalP=0,totalE=0,mode='plan',result=false,recorded=false}
  s.screen='fight'; s.notice=nil; G.forecast(s)
end
local function addlog(m,t) m.log[#m.log+1]=t if #m.log>24 then table.remove(m.log,1) end end
local function inrange(d,r) for _,v in ipairs(r) do if v==d then return true end end return false end
local function damage(m,a,b,id,def)
  local d=G.actions[id]
  if not d.damage then return 0,0,'',false end
  if not inrange(m.distance,d.range) then return 0,0,'거리 밖',false end
  if def=='slip' and (id=='jab' or id=='cross') then return 0,0,'슬립 회피',true end
  local n=d.damage+a.power
  if a.style=='pressure' and (id=='hook' or id=='body') then n=n+2 end
  if a.combo=='slip' or (a.combo=='jab' and id=='cross') then n=n+4 end
  if a.combo=='feint' then n=n+2 end
  local drain=d.kind=='body' and 7 or 0
  local note='적중'
  if not a.opening then
    if def=='guard' and d.kind=='head' then n=n*0.3; note='가드'
    elseif def=='low' and d.kind=='body' then n=n*0.2; drain=1; note='바디 방어'
    elseif def=='low' and d.kind=='head' then n=n*1.2; note='열린 머리'
    elseif def=='pivot' and d.kind=='head' then n=n*0.7; note='피벗 감쇄' end
  else note='페인트 관통' end
  if b.ropes==2 and d.kind=='head' then n=n+1 end
  return math.max(1,math.floor(n+0.5)),drain,note,false
end
local function recover(f,id)
  f.sta=clamp(f.sta+2+(id=='breathe' and 7 or 0),0,f.maxsta)
  f.shock=clamp(f.shock-(id=='breathe' and 3 or 0),0,18)
end
local function available(f,id)
  local c=G.cost(f,id)
  if f.sta<c then return 'breathe',true end
  f.sta=f.sta-c
  return id,false
end
function G.beat(m,pi,ei,beat)
  local p,e=m.p,m.e
  local pa,pfail=available(p,pi); local ea,efail=available(e,ei)
  local pd,ed=G.actions[pa],G.actions[ea]
  local trace={beat=beat,p=pa,e=ea,pOriginal=pi,eOriginal=ei,pDamage=0,eDamage=0}
  local notes={}
  if pfail then notes[#notes+1]='내 호흡 부족 → 호흡으로 전환' end
  if efail then notes[#notes+1]='상대 호흡 부족 → 호흡으로 전환' end
  local delta=0
  local oldP,oldE=p.ropes,e.ropes
  for _,pair in ipairs({{p,e,pa},{e,p,ea}}) do
    local a,b,id=pair[1],pair[2],pair[3]
    if id=='in' then delta=delta-1
    elseif id=='out' then
      if a.ropes<2 then delta=delta+1 else notes[#notes+1]=(a==p and '내' or '상대')..' 로프에 후퇴 막힘' end
    end
  end
  p.ropes=clamp((pa=='pivot' and 0 or oldP)+(pa=='out' and oldP<2 and 1 or 0)+(ea=='in' and 1 or 0),0,2)
  e.ropes=clamp((ea=='pivot' and 0 or oldE)+(ea=='out' and oldE<2 and 1 or 0)+(pa=='in' and 1 or 0),0,2)
  m.distance=clamp(m.distance+delta,0,3)
  local tied=(pa=='clinch' or ea=='clinch') and m.distance<=1
  if tied then
    m.distance=2; p.ropes=0; e.ropes=0
    p.shock=clamp(p.shock-4,0,18); e.shock=clamp(e.shock-4,0,18)
    p.combo=''; e.combo=''; p.opening=false; e.opening=false
    notes[#notes+1]='클린치 · 공격 중단, 중앙에서 분리'
  else
    -- Both impacts are calculated from the same pre-impact state: no first-player advantage.
    local pn,pe,pt,eslip=damage(m,p,e,pa,ea)
    local en,ep,et,pslip=damage(m,e,p,ea,pa)
    trace.pDamage=pn; trace.eDamage=en
    p.hp=clamp(p.hp-en,0,p.maxhp); e.hp=clamp(e.hp-pn,0,e.maxhp)
    p.sta=clamp(p.sta-ep,0,p.maxsta); e.sta=clamp(e.sta-pe,0,e.maxsta)
    if pd.kind=='head' then e.shock=clamp(e.shock+math.floor(pn*0.55),0,18) end
    if ed.kind=='head' then p.shock=clamp(p.shock+math.floor(en*0.55),0,18) end
    p.rdDamage=p.rdDamage+pn; e.rdDamage=e.rdDamage+en
    p.damage=p.damage+pn; e.damage=e.damage+en
    if pn>0 then p.hits=p.hits+1 end if en>0 then e.hits=e.hits+1 end
    p.combo=pslip and 'slip' or (pa=='jab' and pn>0 and 'jab') or (pa=='feint' and 'feint') or ''
    e.combo=eslip and 'slip' or (ea=='jab' and en>0 and 'jab') or (ea=='feint' and 'feint') or ''
    p.opening=pa=='feint' and (ea=='guard' or ea=='low')
    e.opening=ea=='feint' and (pa=='guard' or pa=='low')
    if pt~='' then notes[#notes+1]='내 '..G.actions[pa].name..' '..pt..' '..pn end
    if et~='' then notes[#notes+1]='상대 '..G.actions[ea].name..' '..et..' '..en end
    if pa=='clinch' or ea=='clinch' then notes[#notes+1]='멀어서 클린치 실패' end
  end
  -- A knockout takes priority over recovery; shock knockdowns interrupt the remaining beats.
  if p.hp<=0 or e.hp<=0 then
    m.result={winner=p.hp<=0 and (e.hp<=0 and 'draw' or 'enemy') or 'player',method='KO'}
  else
    for _,f in ipairs({p,e}) do
      if f.shock>=18 then
        f.downs=f.downs+1; f.rdDowns=f.rdDowns+1; f.shock=0; f.combo=''; f.opening=false
        trace.down=true; notes[#notes+1]=(f==p and '내' or '상대')..' 다운 · 카운트 8에 기립'
      end
    end
    if p.downs>=3 or e.downs>=3 then
      m.result={winner=p.downs>=3 and (e.downs>=3 and 'draw' or 'enemy') or 'player',method='TKO'}
    end
    if trace.down then
      m.distance=2; p.ropes=0; e.ropes=0; p.combo=''; e.combo=''; p.opening=false; e.opening=false
    end
  end
  recover(p,pa); recover(e,ea)
  trace.distance=m.distance; trace.notes=table.concat(notes,' · ')
  if trace.notes=='' then trace.notes='서로 간격과 호흡을 조정합니다.' end
  addlog(m,'R'..m.round..' / '..m.exchange..'-'..beat..' · '..trace.notes)
  return trace
end
function G.scoreRound(m)
  local p,e=m.p,m.e
  local winner=p.rdDamage==e.rdDamage and 'draw' or (p.rdDamage>e.rdDamage and 'player' or 'enemy')
  local ps,es=10,10
  if winner=='player' then es=9 elseif winner=='enemy' then ps=9 end
  ps=math.max(7,ps-p.rdDowns); es=math.max(7,es-e.rdDowns)
  -- Normalize to the game's ten-point must card after knockdown deductions.
  if ps>es then ps=10 elseif es>ps then es=10 else ps=10; es=10 end
  m.cards[#m.cards+1]={round=m.round,p=ps,e=es,pDamage=p.rdDamage,eDamage=e.rdDamage,pDowns=p.rdDowns,eDowns=e.rdDowns}
  m.totalP=m.totalP+ps; m.totalE=m.totalE+es
end
local function record(s)
  local m=s.match
  if m.recorded then return end
  m.recorded=true
  local won=m.result.winner=='player'
  if won then s.wins=s.wins+1 else s.losses=s.losses+(m.result.winner=='enemy' and 1 or 0) end
  s.records[#s.records+1]={level=s.level,winner=m.result.winner,method=m.result.method,p=m.totalP,e=m.totalE}
  if #s.records>30 then table.remove(s.records,1) end
  if won then s.points=s.points+2 end
end
function G.execute(s)
  local m=s.match
  if not m or m.mode~='plan' or #m.plan~=3 or m.result then return false end
  for _,id in ipairs(m.plan) do if not G.actions[id] then return false end end
  m.last={}; m.lastFirst=m.plan[1]
  for i=1,3 do
    local row=G.beat(m,m.plan[i],m.intent[i],i); m.last[#m.last+1]=row
    if row.down or m.result then break end
  end
  m.turn=m.turn+1; m.plan={}; m.mode='replay'
  if m.exchange==4 or m.result then
    G.scoreRound(m)
    if not m.result and m.round==m.rounds then
      m.result={winner=m.totalP==m.totalE and 'draw' or (m.totalP>m.totalE and 'player' or 'enemy'),method='판정'}
    end
  end
  if m.result then record(s) end
  return true
end
function G.continue(s)
  local m=s.match
  if not m or m.mode~='replay' then return false end
  if m.result then s.screen='result'
  elseif m.exchange==4 then m.mode='corner'
  else m.exchange=m.exchange+1; m.mode='plan'; G.forecast(s) end
  return true
end
function G.corner(s,id)
  local m=s.match
  if not m or m.mode~='corner' or not ({ice=true,air=true,read=true})[id] then return false end
  for _,f in ipairs({m.p,m.e}) do
    f.sta=clamp(f.sta+10,0,f.maxsta); f.shock=clamp(f.shock-6,0,18)
    f.ropes=0; f.combo=''; f.opening=false; f.rdDamage=0; f.rdDowns=0
  end
  if id=='ice' then m.p.hp=clamp(m.p.hp+14,0,m.p.maxhp)
  elseif id=='air' then m.p.sta=m.p.maxsta; m.p.shock=0
  elseif id=='read' then m.p.combo='feint'; m.p.opening=true end
  m.e.hp=clamp(m.e.hp+6,0,m.e.maxhp)
  m.round=m.round+1; m.exchange=1; m.distance=2; m.mode='plan'; G.forecast(s)
  return true
end
function G.project(s)
  local m=copy(s.match); local start=m.p.sta
  local rows={}
  for i,id in ipairs(m.plan) do
    local cost=G.cost(m.p,id); local low=m.p.sta<cost
    local row=G.beat(m,id,m.intent[i],i)
    rows[#rows+1]={sta=m.p.sta,low=low}
    if m.result or row.down then break end
  end
  return rows,start
end
-- Every mutating button includes a revision. Old UI and double-clicks are harmless.
function G.reduce(s,action,value)
  local m=s.match
  s.notice=nil
  if action=='help' then s.help=not s.help; return true end
  if action=='resetAsk' then s.resetPending=true; return true end
  if action=='resetCancel' then s.resetPending=false; return true end
  if action=='resetYes' and s.resetPending then
    local n=G.new(s.seed,s.serial+1); n.revision=s.revision
    for k in pairs(s) do s[k]=nil end for k,v in pairs(n) do s[k]=v end return true
  end
  if s.resetPending then return false end
  if action=='style' and s.screen=='home' then
    for _,v in ipairs(G.styles) do if v.id==value then s.style=value; return true end end
  elseif action=='career' and s.screen=='home' then s.screen='gym'; return true
  elseif action=='train' and s.screen=='gym' and s.points>0 then
    for _,u in ipairs(G.upgrades) do if u.id==value and s.upgrades[value]<u.max then s.upgrades[value]=s.upgrades[value]+1; s.points=s.points-1; return true end end
  elseif action=='start' and s.screen=='gym' then G.start(s); return true
  elseif action=='add' and s.screen=='fight' and m.mode=='plan' and #m.plan<3 and G.actions[value] then m.plan[#m.plan+1]=value; return true
  elseif action=='undo' and s.screen=='fight' and m.mode=='plan' and #m.plan>0 then table.remove(m.plan); return true
  elseif action=='clear' and s.screen=='fight' and m.mode=='plan' then m.plan={}; return true
  elseif action=='execute' and s.screen=='fight' then return G.execute(s)
  elseif action=='continue' and s.screen=='fight' then return G.continue(s)
  elseif action=='corner' and s.screen=='fight' then return G.corner(s,value)
  elseif action=='resultNext' and s.screen=='result' and m.result then
    if m.result.winner=='player' then
      if s.level==#G.rivals then s.screen='champion' else s.level=s.level+1; s.screen='gym' end
    else s.screen='gym' end
    return true
  end
  return false
end

local function esc(v) return (tostring(v or ''):gsub('&','&amp;'):gsub('<','&lt;'):gsub('>','&gt;'):gsub('"','&quot;'):gsub("'",'&#39;')) end
local function div(cls,content) return '<div class="x-risu-lb-'..cls:gsub(' ',' x-risu-lb-')..'">'..content..'</div>' end
local function tag(v) return '<span class="x-risu-lb-eyebrow">'..v..'</span>' end
local function title(k,t,p) return tag(k)..'<h2>'..t..'</h2>'..(p and '<p>'..p..'</p>' or '') end
local function btn(s,action,value,label,cls,disabled)
  return '<button type="button" class="x-risu-lb-btn '..(cls and 'x-risu-lb-'..cls:gsub(' ',' x-risu-lb-') or '')..'"'..
    (disabled and ' disabled aria-disabled="true"' or ' risu-btn="lb;'..s.serial..';'..s.revision..';'..action..';'..(value or '')..'"')..'>'..label..'</button>'
end
local function stat(label,value) return div('stat','<small>'..label..'</small><strong>'..value..'</strong>') end
local function meter(name,value,max,cls)
  return '<div class="x-risu-lb-meter"><div><span>'..name..'</span><b>'..value..'<small> / '..max..'</small></b></div><div class="x-risu-lb-track"><i class="x-risu-lb-'..cls..'" style="width:'..G.clamp(math.floor(value/max*100),0,100)..'%"></i></div></div>'
end
local function figure(side)
  return '<div class="x-risu-lb-boxer x-risu-lb-'..side..'" aria-hidden="true"><i class="x-risu-lb-head"></i><i class="x-risu-lb-torso"></i><i class="x-risu-lb-glove x-risu-lb-glove-a"></i><i class="x-risu-lb-glove x-risu-lb-glove-b"></i><i class="x-risu-lb-leg x-risu-lb-leg-a"></i><i class="x-risu-lb-leg x-risu-lb-leg-b"></i></div>'
end
local function arena(s,hero)
  local r=G.rivals[s.level]; local d=s.match and s.match.distance or 2
  return '<div class="x-risu-lb-arena '..(hero and 'x-risu-lb-hero' or '')..' x-risu-lb-distance-'..d..'">'..
    div('arena-top',tag('SEOUL / AFTER HOURS')..'<span>'..r.venue..'</span>')..
    div('ring-word',hero and 'LAST<br>BELL' or 'ROUND<br>'..string.format('%02d',s.match.round))..
    '<div class="x-risu-lb-rope x-risu-lb-rope-one"></div><div class="x-risu-lb-rope x-risu-lb-rope-two"></div><div class="x-risu-lb-rope x-risu-lb-rope-three"></div>'..
    figure('you')..figure('opponent')..div('canvas-mark','L B / 01')..
    div('arena-bottom','<span>BLUE CORNER · YOU</span><span>'..r.alias..' · RED</span>')..'</div>'
end
local function map(s)
  local h={}
  for i,r in ipairs(G.rivals) do
    h[#h+1]='<div class="x-risu-lb-stop '..(i==s.level and 'x-risu-lb-current' or '')..'">'..
      '<b>'..(i<s.level and '✓' or string.format('%02d',i))..'</b><span>'..r.name..'<small>'..r.venue..'</small></span></div>'
  end
  return div('route',table.concat(h))
end
local function guide()
  return '<details class="x-risu-lb-guide" open><summary>코너 노트 · 플레이 방법</summary>'..
    '<p><b>① 읽기</b> 상대의 3박자 행동은 확정 예고입니다. <b>② 배치</b> 행동 버튼으로 내 3박자를 채웁니다. <b>③ 실행</b> 각 박자는 이동 → 동시 타격 → 회복 순서로 해결됩니다.</p>'..
    '<p><b>거리</b> 0 밀착 / 1 포켓 / 2 잽 거리 / 3 아웃사이드. 전진은 거리 -1, 후퇴는 +1. 양쪽 이동은 합산됩니다. 로프 압박 2에서는 후퇴가 막히므로 피벗하세요.</p>'..
    '<p><b>연결</b> 잽 적중 → 스트레이트 +4. 슬립 성공 → 다음 펀치 +4. 페인트 → 다음 펀치 +2; 페인트 때 상대가 가드했다면 다음 펀치는 가드를 관통합니다. 연결은 바로 다음 박자에만 적용됩니다.</p>'..
    '<p><b>호흡</b> 매 박자 +2, 호흡 행동은 추가 +7. 행동 비용을 낼 수 없으면 호흡으로 전환됩니다. 바디는 체력과 호흡을 함께 깎습니다.</p>'..
    '<p><b>승리</b> 체력 0은 KO, 충격 18은 다운이며 남은 박자를 중단합니다. 한 경기 누적 3다운은 TKO입니다. 1라운드 = 4교환 × 최대 3박자. 제한 라운드 뒤에는 표시된 점수표로 판정합니다.</p>'..
    '<p><b>채점</b> 라운드 총 피해 우세가 10–9, 같으면 10–10. 다운 1회마다 다운된 선수 -1점(최저 7), 높은 쪽은 10점으로 정규화합니다. KO 라운드도 기록용 점수를 남기지만 승패는 KO가 우선합니다. 실제 대회 규정과 다른 게임 전용 채점입니다.</p>'..
    '<p><b>코너</b> 양쪽 호흡 +10·충격 -6, 상대 체력 +6. 나는 치료(+14 체력), 회복(호흡 최대·충격 0), 읽기(첫 박자 +2·가드 관통) 중 하나를 고릅니다. 다음 경기에는 체력과 호흡이 완전히 회복됩니다.</p>'..
    '<p>자동 저장은 현재 채팅에 연결됩니다. 오래된 화면의 버튼은 무효입니다. <b>/boxing</b> 또는 <b>/lastbell</b>로 패널을 다시 열 수 있습니다. 일반 메시지는 원래 채팅대로 처리됩니다.</p></details>'
end
local function home(s)
  local h={arena(s,true),div('intro',title('A THREE-BEAT BOXING GAME','마지막 종이 울리기 전.','세 박자를 읽고, 빈틈 하나를 만든다.<br>동네 체육관에서 미드나이트 타이틀까지.'))}
  h[#h+1]=div('features',stat('시스템','3박자 계획')..stat('커리어','5명의 라이벌')..stat('플레이','버튼 · 자동 저장'))
  h[#h+1]='<h3>당신의 복싱</h3><div class="x-risu-lb-styles">'
  for _,style in ipairs(G.styles) do
    h[#h+1]=btn(s,'style',style.id,tag(style.tag)..'<b>'..style.name..'</b><small>'..style.desc..'</small>',s.style==style.id and 'style selected' or 'style')
  end
  h[#h+1]='</div>'..btn(s,'career','','커리어 시작 <span>→</span>','primary')
  h[#h+1]=div('footnote','결과는 거리와 행동으로 결정됩니다. 명중 주사위·AI 호출·외부 서버가 없습니다.')
  return table.concat(h)
end
local function gym(s)
  local r=G.rivals[s.level]; local h={title('THE ROAD / '..string.format('%02d',s.level),'다음 링으로.','훈련을 고르고 상대의 습관을 읽으세요.'),map(s)}
  h[#h+1]=div('scout',tag('SCOUTING REPORT / '..r.rounds..' ROUNDS')..'<h3>'..r.name..' <small>'..r.alias..'</small></h3><blockquote>“'..r.quote..'”</blockquote><p>'..r.lesson..'</p>')
  h[#h+1]=div('section-head','<h3>오늘의 훈련</h3><span>훈련 포인트 <b>'..s.points..'</b></span>')..'<div class="x-risu-lb-training">'
  for _,u in ipairs(G.upgrades) do h[#h+1]=btn(s,'train',u.id,'<b>'..u.name..'</b><small>'..u.desc..'</small><span>'..s.upgrades[u.id]..' / '..u.max..' · 1P</span>','training-card',s.points<1 or s.upgrades[u.id]>=u.max) end
  h[#h+1]='</div><p class="x-risu-lb-subtle">승리마다 2P. 패배·무승부는 훈련을 유지하고 같은 상대에게 재도전합니다.</p>'
  h[#h+1]=btn(s,'start','','링에 오르기 <span>→</span>','primary')
  return table.concat(h)
end
local function fighter(f,name,side)
  local status=f.combo=='slip' and '회피 연결 +4' or f.combo=='jab' and '스트레이트 연결 +4' or f.combo=='feint' and '페인트 연결 +2' or '연결 없음'
  return div('fighter',div('fighter-name',tag(side)..'<b>'..name..'</b>')..meter('체력',f.hp,f.maxhp,'health')..meter('호흡',f.sta,f.maxsta,'energy')..meter('충격',f.shock,18,'shock')..
    div('fighter-meta','<span>다운 <b>'..f.downs..'/3</b></span><span>로프 <b>'..f.ropes..'/2</b></span>')..
    div('status',status..(f.opening and ' · 가드 관통' or '')))
end
local function ranges(m)
  local h={}
  for i,v in ipairs({'밀착','포켓','잽 거리','아웃사이드'}) do h[#h+1]='<span class="'..(m.distance==i-1 and 'x-risu-lb-range-active' or '')..'"><b>'..i-1 ..'</b>'..v..'</span>' end
  return div('range',table.concat(h))
end
local function score(m)
  if #m.cards==0 then return '<p class="x-risu-lb-subtle">첫 라운드 종료 후 점수가 기록됩니다.</p>' end
  local h={'<table class="x-risu-lb-score"><caption>공개 점수표</caption><thead><tr><th>라운드</th><th>나</th><th>상대</th><th>가한 피해</th></tr></thead><tbody>'}
  for _,c in ipairs(m.cards) do h[#h+1]='<tr><td>R'..c.round..'</td><td>'..c.p..'</td><td>'..c.e..'</td><td>'..c.pDamage..' : '..c.eDamage..'</td></tr>' end
  h[#h+1]='</tbody><tfoot><tr><th>합계</th><th>'..m.totalP..'</th><th>'..m.totalE..'</th><td></td></tr></tfoot></table>'
  return table.concat(h)
end
local function plan(s)
  local m=s.match; local h={div('section-head','<h3>상대의 다음 3박자</h3>'..tag('INTENT / LOCKED')),'<div class="x-risu-lb-beats">'}
  for i,id in ipairs(m.intent) do local a=G.actions[id]
    h[#h+1]=div('intent','<small>0'..i..' · '..a.short..'</small><b>'..a.name..'</b><span>'..a.tip..'</span>')
  end
  h[#h+1]='</div>'
  if m.adapt~='' then h[#h+1]=div('callout',m.adapt) end
  h[#h+1]=div('section-head','<h3>나의 3박자</h3><span>'..#m.plan..' / 3 배치</span>')..'<div class="x-risu-lb-beats">'
  for i=1,3 do local id=m.plan[i]
    h[#h+1]=div('slot'..(id and ' filled' or ''),'<small>0'..i..'</small><b>'..(id and G.actions[id].name or '행동 선택')..'</b><span>'..(id and '호흡 -'..G.cost(m.p,id) or '아래 버튼으로 채우세요')..'</span>')
  end
  h[#h+1]='</div>'..div('plan-tools',btn(s,'undo','','마지막 취소',nil,#m.plan==0)..btn(s,'clear','','모두 비우기',nil,#m.plan==0))
  h[#h+1]='<div class="x-risu-lb-actions">'
  for _,id in ipairs(G.order) do local a=G.actions[id]
    h[#h+1]=btn(s,'add',id,'<span><b>'..a.name..'</b><em>−'..G.cost(m.p,id)..'</em></span><small>'..a.tip..'</small>','action',#m.plan==3)
  end
  h[#h+1]='</div>'
  local rows=G.project(s); local low=false
  for _,v in ipairs(rows) do if v.low then low=true end end
  if low then h[#h+1]=div('callout','이 계획은 도중에 호흡이 부족해질 수 있습니다. 부족한 행동은 자동으로 호흡으로 바뀝니다.') end
  h[#h+1]=btn(s,'execute','','3박자 실행 <span>→</span>','primary',#m.plan~=3)
  return table.concat(h)
end
local function replay(s)
  local m=s.match; local h={title('EXCHANGE / REPLAY','방금, 링 위에서.','각 박자의 이동과 타격을 동시에 계산한 결과입니다.')}
  for _,row in ipairs(m.last) do
    h[#h+1]=div('replay-row','<b class="x-risu-lb-beat-num">0'..row.beat..'</b><div><strong>'..G.actions[row.p].name..' <span>vs</span> '..G.actions[row.e].name..'</strong><p>'..row.notes..'</p></div><span class="x-risu-lb-impact">'..row.pDamage..' <small>/ '..row.eDamage..'</small></span>')
  end
  if #m.last<3 then h[#h+1]=div('callout','다운 또는 경기 종료로 남은 박자를 중단했습니다.') end
  h[#h+1]=btn(s,'continue','',m.result and '경기 결과 보기 →' or (m.exchange==4 and '코너로 돌아가기 →' or '다음 교환 계획 →'),'primary')
  return table.concat(h)
end
local function corner(s)
  local m=s.match
  return div('corner',title('BETWEEN ROUNDS','숨을 고르는 시간.','R'..m.round..' 종료. 기본 회복 후 아래 선택 하나가 다음 라운드에 적용됩니다.')..score(m)..
    div('corner-options',btn(s,'corner','ice','<b>차가운 수건</b><small>체력 +14. 맞교환으로 지친 몸을 치료합니다.</small>','choice')..
    btn(s,'corner','air','<b>깊게, 한 번 더</b><small>호흡 최대·충격 0. 다운 위기를 끊습니다.</small>','choice')..
    btn(s,'corner','read','<b>약점을 짚어 줘</b><small>첫 박자 펀치 +2·가드 관통. 시작부터 빈틈을 찌릅니다.</small>','choice')))
end
local function fight(s)
  local m=s.match; local r=G.rivals[s.level]
  local h={div('bout-heading',tag('BOUT '..string.format('%02d',s.level)..' / '..r.venue)..'<b>R'..m.round..' / '..m.rounds..' <small>교환 '..m.exchange..' / 4</small></b>'),arena(s),
    div('fighters',fighter(m.p,'당신','BLUE CORNER')..fighter(m.e,r.name,r.alias)),ranges(m)}
  if m.mode=='plan' then h[#h+1]=plan(s) elseif m.mode=='replay' then h[#h+1]=replay(s) else h[#h+1]=corner(s) end
  h[#h+1]='<details class="x-risu-lb-details"><summary>스카우팅 · 점수표 · 경기 기록</summary><p>'..r.lesson..'</p>'..score(m)
  for i=#m.log,1,-1 do h[#h+1]='<p class="x-risu-lb-log">'..esc(m.log[i])..'</p>' end
  h[#h+1]='</details>'
  return table.concat(h)
end
local function result(s)
  local m=s.match; local r=m.result; local won=r.winner=='player'
  return div('result',tag(r.method..' / OFFICIAL RESULT')..'<h2>'..(won and '당신의 라운드.' or r.winner=='draw' and '아직, 끝나지 않았다.' or '다시 일어설 시간.')..'</h2><p>'..(won and G.rivals[s.level].name..'에게 승리했습니다. 훈련 포인트 +2.' or '훈련 기록은 유지됩니다. 상대의 예고를 다시 읽고 재도전하세요.')..'</p>'..
    div('features',stat('가한 피해',m.p.damage)..stat('적중',m.p.hits)..stat('내 다운',m.p.downs))..score(m)..
    btn(s,'resultNext','',won and (s.level==5 and '챔피언 벨트 받기 →' or '다음 라이벌 →') or '체육관으로 →','primary'))
end
function G.render(s)
  local h={'<div class="x-risu-lb" lang="ko"><header class="x-risu-lb-header"><b>LB<span> / LAST BELL</span></b><span>TURN-BASED BOXING</span></header><main class="x-risu-lb-main">'}
  if s.resetPending then
    h[#h+1]=div('callout','<h3>커리어를 새로 시작할까요?</h3><p>현재 채팅의 경기·훈련·전적이 초기화됩니다.</p>'..btn(s,'resetYes','','초기화하고 시작','danger')..btn(s,'resetCancel','','돌아가기'))
  elseif s.screen=='home' then h[#h+1]=home(s)
  elseif s.screen=='gym' then h[#h+1]=gym(s)
  elseif s.screen=='fight' then h[#h+1]=fight(s)
  elseif s.screen=='result' then h[#h+1]=result(s)
  elseif s.screen=='champion' then
    h[#h+1]=arena(s,true)..div('result',title('MIDNIGHT CHAMPION','마지막까지, 서 있었다.','다섯 개의 링을 지나 챔피언이 되었습니다. 당신의 리듬이 이 도시의 밤에 남습니다.')..div('belt','★  LAST BELL CHAMPION  ★')..div('features',stat('승리',s.wins)..stat('패배',s.losses)..stat('클리어','5 / 5'))..btn(s,'resetAsk','','다른 스타일로 새 커리어','primary'))
  end
  if s.help then h[#h+1]=guide() end
  h[#h+1]='</main><footer class="x-risu-lb-footer"><span>A LOCAL BOXING STORY · v1.0</span><div>'..btn(s,'help','',s.help and '설명 닫기' or '플레이 방법')..btn(s,'resetAsk','','새 커리어')..'</div></footer></div>'
  return table.concat(h)
end

local function load(id)
  local ok,s=pcall(getState,id,G.key)
  if not ok or type(s)~='table' then return G.new() end
  if s.version~=G.version then return nil end
  return s
end
function G.handle(id,code)
  if type(code)~='string' then return end
  local serial,rev,action,value=code:match('^lb;(%d+);(%d+);([%a]+);([%w_]*)$')
  if not action then return end
  local s=load(id)
  if not s or s.serial~=tonumber(serial) or s.revision~=tonumber(rev) then return end
  if G.reduce(s,action,value) then
    s.revision=s.revision+1
    setState(id,G.key,s)
    if reloadDisplay then reloadDisplay(id) end
  end
end
listenEdit('editDisplay',function(id,data,meta)
  if meta and meta.index~=nil and meta.index~=getChatLength(id)-1 then return data end
  local s=load(id)
  if not s then return data..'\n\n<div>LAST BELL: 더 새로운 버전의 저장입니다. 최신 모듈을 사용하세요.</div>' end
  return data..'\n\n'..G.render(s)
end)
onButtonClick=async and async(G.handle) or G.handle
onStart=function(id)
  local chat=getFullChat(id); local last=chat[#chat]
  if not last or last.role~='user' then return end
  local cmd=last.data:match('^%s*(.-)%s*$')
  if cmd~='/boxing' and cmd~='/lastbell' then return end
  removeChat(id,getChatLength(id)-1)
  addChat(id,'char','LAST BELL · 링 사이드에 오신 것을 환영합니다.')
  stopChat(id)
end
if LAST_BELL_TEST then LAST_BELL=G end
