"""Build self-contained RisuAI .risum + companion .charx using Python stdlib only."""
from pathlib import Path
import hashlib
import json
import struct
import zipfile

ROOT = Path(__file__).resolve().parent
# RisuAI RPack's byte substitution, required by the public legacy module format.
# Protocol reference: https://github.com/kwaroran/RisuAI/tree/main/src/ts/rpack
DECODE = bytes.fromhex(
    '2cf7848bc965fbb69faeb3032d0169741fe4a3ecee5c3421934a0f6ae262029e'
    '229cfd3cfc71c7c6ad596705706d8a4412fa24865fafd17a47cefe5063dd5106'
    '6f18e052a8099d56734cb8536cc3a00e19cf3e0d7e07326846ea48f9992eaba4'
    '49205e5535380cbcd3b1581679280a1ae1f2cdc439dba2ba6072767d95ef7fc8'
    'c0de3794bfb51481922545ace7f566a72b365ac113e34b3ae88d831b7c27b09a'
    '42eb87aadc548e7826d25729d4b7f82f8f8975f04177c21effd81511e5049717'
    'f331d09b00d7cab44f2a3bd9b26bda5da13f3061bd913d4ee6dfbe4d828c1d23'
    '109864f485337b9043bba988f1d6a51cf6cc6eb95b0b96edd5e9c5cb08a68040'
)
assert len(DECODE) == len(set(DECODE)) == 256
ENCODE = bytes(DECODE.index(i) for i in range(256))


def encode_module(module):
    raw = json.dumps({'type': 'risuModule', 'module': module}, ensure_ascii=False, separators=(',', ':')).encode()
    return b'\x6f\x00' + struct.pack('<I', len(raw)) + raw.translate(ENCODE) + b'\x00'


def decode_module(raw):
    assert raw[:2] == b'\x6f\x00'
    n = struct.unpack_from('<I', raw, 2)[0]
    assert len(raw) == n + 7 and raw[-1] == 0
    decoded = json.loads(raw[6:6+n].translate(DECODE))
    assert decoded['type'] == 'risuModule'
    return decoded['module']


def build():
    out = ROOT / 'release'
    out.mkdir(exist_ok=True)
    lua = '-- LAST BELL 1.0.0 / generated by build.py\n' + '\n'.join(
        (ROOT / 'src' / f).read_text(encoding='utf-8') for f in ['data.lua', 'engine.lua', 'ui.lua', 'risu.lua'])
    css = '<style>\n' + (ROOT / 'src/style.css').read_text(encoding='utf-8') + '\n</style>'
    module = {
        'name': 'LAST BELL · 마지막 종',
        'description': '3박자 계획형 턴제 복싱. 5명 라이벌, 훈련, 거리·로프·연결, 코너와 공개 판정. /boxing으로 시작. AI 호출 없이 작동.',
        'id': '02801fe9-53c8-4ad9-8b58-f18f5e68296d',
        'namespace': 'last_bell_boxing_v1',
        'lowLevelAccess': False, 'hideIcon': False,
        'lorebook': [], 'regex': [], 'assets': [],
        'backgroundEmbedding': css,
        'trigger': [{'comment': 'Last Bell game and UI', 'type': 'manual', 'conditions': [],
                     'effect': [{'type': 'triggerlua', 'code': lua, 'indent': 0}], 'lowLevelAccess': False}],
    }
    raw = encode_module(module)
    (out / 'Last-Bell.risum').write_bytes(raw)
    # A clean companion card: no copied portraits, prompts, lorebooks, or game data.
    card = {'spec': 'chara_card_v3', 'spec_version': '3.0', 'data': {
        'name': 'LAST BELL · 마지막 종', 'description': module['description'],
        'personality': '', 'scenario': '',
        'first_mes': 'LAST BELL · 마지막 종\n\n아래 패널에서 복싱 스타일을 고르고 커리어를 시작하세요. 패널이 안 보이면 /boxing을 입력하세요.',
        'mes_example': '', 'creator_notes': 'Lua 게임입니다. 버튼 플레이에는 API 키나 모델 설정이 필요하지 않습니다. 별도 .risum과 이 카드를 동시에 적용하지 마세요.',
        'system_prompt': '', 'post_history_instructions': '', 'alternate_greetings': [],
        'tags': ['Game', 'Boxing', 'Korean', 'Lua'], 'creator': 'Last Bell', 'character_version': '1.0.0',
        'group_only_greetings': [], 'assets': [],
        'extensions': {'risuai': {'backgroundHTML': css}},
    }}
    with zipfile.ZipFile(out / 'Last-Bell-Standalone.charx', 'w', zipfile.ZIP_DEFLATED) as z:
        for name, data in [('card.json', json.dumps(card, ensure_ascii=False, indent=2).encode()), ('module.risum', raw)]:
            info = zipfile.ZipInfo(name, (2026, 9, 8, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            z.writestr(info, data)
    (out / 'Last-Bell.lua').write_text(lua, encoding='utf-8')
    assert decode_module(raw) == module
    with zipfile.ZipFile(out / 'Last-Bell-Standalone.charx') as z:
        assert z.testzip() is None
        assert decode_module(z.read('module.risum')) == module
        assert json.loads(z.read('card.json')) == card
    manifest = {p.name: {'bytes': p.stat().st_size, 'sha256': hashlib.sha256(p.read_bytes()).hexdigest()}
                for p in [out/'Last-Bell.risum', out/'Last-Bell-Standalone.charx', out/'Last-Bell.lua']}
    (out / 'manifest.json').write_text(json.dumps(manifest, indent=2), encoding='utf-8')
    print(json.dumps(manifest, indent=2))


if __name__ == '__main__':
    build()
